apiVersion: v1
kind: Service
metadata:
  labels:
    component: $APP_NAME
  name: $APP_NAME
  namespace: $NAMESPACE
spec:
  ports:
    - name: http
      port: $APP_PORT
      protocol: TCP
      targetPort: $APP_PORT
  selector:
    app: $APP_NAME
  sessionAffinity: None
  type: NodePort
