apiVersion: v1
kind: Service
metadata:
  labels:
    component: myapp-demo
  name: myapp-demo
  namespace: test-zxs
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30863
  selector:
    app: myapp-demo
  sessionAffinity: None
  type: NodePort
